---
seed_everything: 42

model:
  class_path: models.LitIBC

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001

trainer:
  accelerator: gpu
  max_epochs: -1
  gradient_clip_val: 10
  precision: 16-mixed
  log_every_n_steps: 1
  logger:
    class_path: WandbLogger
    init_args:
      log_model: false
      project: ibc-test
      save_dir: tmp
  callbacks:
    -
      class_path: EarlyStopping
      init_args:
        monitor: val_loss
        patience: 200
        mode: min
        verbose: True
    -
      class_path: models.LogLitIBC
      init_args:
        every_n_epochs: 200
        num_samples: 2

data:
  class_path: dataset.CircleDataModule
  init_args:
    train_size: 16
    val_size: 4
    num_points: 50
    batch_size: 8
